"""
ComfyUI Utilitools - Main Node Registry

Centralized registration of all utility nodes organized by category.
"""

from .math import NODE_CLASS_MAPPINGS as MATH_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MATH_DISPLAY_MAPPINGS
from .text import NODE_CLASS_MAPPINGS as TEXT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TEXT_DISPLAY_MAPPINGS
from .conversion import NODE_CLASS_MAPPINGS as CONVERSION_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CONVERSION_DISPLAY_MAPPINGS
from .logic import NODE_CLASS_MAPPINGS as LOGIC_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOGIC_DISPLAY_MAPPINGS
from .data import NODE_CLASS_MAPPINGS as DATA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DATA_DISPLAY_MAPPINGS
from .workflow import NODE_CLASS_MAPPINGS as WORKFLOW_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WORKFLOW_DISPLAY_MAPPINGS
from .constants import NODE_CLASS_MAPPINGS as CONSTANTS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CONSTANTS_DISPLAY_MAPPINGS
from .image import NODE_CLASS_MAPPINGS as IMAGE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **MATH_MAPPINGS,
    **TEXT_MAPPINGS,
    **CONVERSION_MAPPINGS,
    **LOGIC_MAPPINGS,
    **DATA_MAPPINGS,
    **WORKFLOW_MAPPINGS,
    **CONSTANTS_MAPPINGS,
    **IMAGE_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **MATH_DISPLAY_MAPPINGS,
    **TEXT_DISPLAY_MAPPINGS,
    **CONVERSION_DISPLAY_MAPPINGS,
    **LOGIC_DISPLAY_MAPPINGS,
    **DATA_DISPLAY_MAPPINGS,
    **WORKFLOW_DISPLAY_MAPPINGS,
    **CONSTANTS_DISPLAY_MAPPINGS,
    **IMAGE_DISPLAY_MAPPINGS,
}